# source: docs/continuous-delivery/gitops/security/secret-injection-harness-plugin.md  (https://developer.harness.io/docs/continuous-delivery/gitops/security/secret-injection-harness-plugin)

# --- example 1 ---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: default
type: Opaque
stringData:
  vault-value: <+secrets.getValue("vault_secret")>

# --- example 2 ---
apiVersion: v1
kind: Secret
metadata:
  name: harness-secrets
  namespace: default
type: Opaque
stringData:
  harness-value: <+secrets.getValue("harness_secret_manager_secret")>

# --- example 3 ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
secrets:
- name: <+secrets.getValue("service_account_token")>

# --- example 4 ---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  vault-value: <+secrets.getValue("vault_secret")>
  harness-value: <+secrets.getValue("harness_secret")>
