# source: docs/continuous-integration/ci-articles-faqs/continuous-integration-faqs.md  (https://developer.harness.io/docs/continuous-integration/ci-articles-faqs/continuous-integration-faqs)

# --- example 1 ---
connector:
  name: ExampleDockerConnector
  identifier: ExampleDockerConnectorId
  description: Example Docker Connector
  orgIdentifier: Doc
  projectIdentifier: Example
  type: DockerRegistry
  spec:
    dockerRegistryUrl: https://registry.hub.docker.com/v2/
    providerType: DockerHub
    auth:
      type: UsernamePassword
      spec:
        username: john.doe@example.com
        passwordRef: docsdockerhubpassword
    ignoreTestConnection: true

# --- example 2 ---
environment:
  - ACCOUNT_ID=XXXX
  - DELEGATE_TOKEN=XXXX
  - MANAGER_HOST_AND_PORT=https://app.harness.io
  - DELEGATE_NAME=test
  - NEXT_GEN=true
  - DELEGATE_TYPE=DOCKER
  - SCM_SKIP_SSL=true

# --- example 3 ---
version: "1"
instances:
  - name: windows-ci-pool
    default: true
    type: amazon
    pool: 1
    limit: 4
    platform:
      os: windows
    spec:
      account:
        region: us-east-2
        availability_zone: us-east-2c
        access_key_id:
        access_key_secret:
        key_pair_name: XXXXX
      ami: ami-088d5094c0da312c0
      size: t3.large ## VM machine size.
      hibernate: true
      network:
        security_groups:
          - sg-XXXXXXXXXXXXXX
      disk:
        size: 100 ## Disk size in GB.
        type: "pd-balanced"

# --- example 4 ---
pipeline:
  identifier: subprocess_demo
  name: subprocess_demo
  projectIdentifier: default
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        identifier: BUild
        type: CI
        name: Build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: Run_1
                  type: Run
                  name: Run_1
                  spec:
                    connectorRef: YOUR_DOCKER_CONNECTOR_ID
                    image: jtapsgroup/javafx-njs:latest
                    shell: Powershell
                    command: |-
                      cd folder
                      gradle --version
                      Start-Process -NoNewWindow -FilePath "powershell" -ArgumentList "Start-Sleep -Seconds 120"
                      Write-Host "Done!"
                    resources:
                      limits:
                        memory: 3Gi
                        cpu: "1"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: YOUR_KUBERNETES_CLUSTER_CONNECTOR_ID
              namespace: YOUR_KUBERNETES_NAMESPACE
              initTimeout: 900s
              automountServiceAccountToken: true
              nodeSelector:
                kubernetes.io/os: windows
              os: Windows
          caching:
            enabled: false
            paths: []
  properties:
    ci:
      codebase:
        connectorRef: YOUR_CODEBASE_CONNECTOR_ID
        build:
          type: branch
          spec:
            branch: main

# --- example 5 ---
variables:
  - name: DATE_FORMATTED ## This variable's value is 'ToString' output.
    type: String
    description: ""
    required: false
    value: (Get-Date).ToString("yyyy.MMdd")
  - name: BUILD_VAR ## This variable's value concatenates the execution ID, the sequence ID, and the value of DATE_FORMATTED.
    type: String
    description: ""
    required: false
    value: <+<+pipeline.executionId>+"-"+<+pipeline.sequenceId>+"-"+<+stage.variables.DATE_FORMATTED>>

# --- example 6 ---
variables:
  - name: DATE_FORMATTED ## This variable is unchanged.
    type: String
    description: ""
    required: false
    value: (Get-Date).ToString("yyyy.MMdd")
  - name: BUILD_VAR ## This variable's value concatenates only the execution ID and sequence ID. It no longer includes DATE_FORMATTED.
    type: String
    description: ""
    required: false
    value: <+<+pipeline.executionId>+"-"+<+pipeline.sequenceId>>

# --- example 7 ---
- step:
    identifier: echo
    type: Run
    name: echo
    spec:
      shell: Powershell
      command:
        |- ## DATE_FORMATTED is resolved separately and then appended to BUILD_VAR.
        $val = <+stage.variables.DATE_FORMATTED>
        echo <+pipeline.stages.test.variables.BUILD_VAR>-$val

# --- example 8 ---
properties:
  ci:
    codebase:
      connectorRef: YOUR_CODEBASE_CONNECTOR_ID
      repoName: YOUR_CODE_REPO_NAME
      build:
        type: branch
        spec:
          branch: <+input>
      sslVerify: false
      resources:
        limits:
          memory: 4G ## Set the maximum memory to use. You can express memory as a plain integer or as a fixed-point number using the suffixes `G` or `M`. You can also use the power-of-two equivalents `Gi` and `Mi`. The default is `500Mi`.
          cpu: "2" ## Set the maximum number of cores to use. CPU limits are measured in CPU units. Fractional requests are allowed; for example, you can specify one hundred millicpu as `0.1` or `100m`.

# --- example 9 ---
pipeline:
  name: blockwebsiteexample
  identifier: blockwebsiteexample
  projectIdentifier: PROJECT_NAME
  orgIdentifier: default
  stages:
    - stage:
        name: test
        identifier: test
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      DOMAIN="example.com"
                      IPS=$(dig +short $DOMAIN | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
                      for IP in $IPS; do
                        sudo iptables -A OUTPUT -d "$IP" -j REJECT
                      done
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: curl -I https://example.com
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Bash
                    command: |-
                      DOMAIN="example.com"
                      IPS=$(dig +short $DOMAIN | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
                      for IP in $IPS; do
                        sudo iptables -D OUTPUT -d "$IP" -j REJECT
                      done
                  when:
                    stageStatus: All
              - step:
                  type: Run
                  name: Run_4
                  identifier: Run_4
                  spec:
                    shell: Sh
                    command: curl -I https://example.com
                  when:
                    stageStatus: All

# --- example 10 ---
package pipeline

# Deny build pipelines that don't push to "us.gcr.io"
# NOTE: Try changing the expected host to see the policy fail
deny[msg] {
	# Find all stages ...
	stage = input.pipeline.stages[_].stage

	# ... that are used for CI
	stage.type == "CI"

	# ... that have steps
	step = stage.spec.execution.steps[_].step

	# ... that build and push to GCR steps
	step.type == "Run"

  contains_keyword := regex.match("\\bdocker pull\\b", step.spec.command) 
  contains_keyword
  # Generate a message indicating the forbidden keyword usage
  msg := sprintf("Step '%s' in stage '%s' contains a docker pull command.", [step.name, stage.name])
}

# --- example 11 ---
variables:
  - name: PLUGIN_DAEMON_OFF
    type: String
    description: ""
    required: false
    value: "true"

# --- example 12 ---
strategy:
  matrix:
    service: [svc1, svc2, svc3]
    env: [env1, env2]
    nodeName: stage_<+matrix.service>_<+matrix.env>
