# source: docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md  (https://developer.harness.io/docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step)

# --- example 1 ---
pipeline:
  stages:
    - stage:
        identifier: tmpStg
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  identifier: tmpScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.stages.tmpStg.spec.execution.steps.tmpScript.spec.environmentVariables.secret_1>
                          echo <+pipeline.stages.tmpStg.spec.execution.steps.tmpScript.spec.environmentVariables.secret_2>
                    environmentVariables:
                      - name: secret_1
                        type: Secret
                        value: temp_secret
                      - name: secret_2
                        type: String
                        value: <+secrets.getValue("temp_secret")>
                    outputVariables: []

# --- example 2 ---
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo hello!
                    environmentVariables: []
                    outputVariables: []
                    includeInfraSelectors: true
                  timeout: 10m

# --- example 3 ---
pipeline:
  name: YOUR_PIPELINE_NAME
  identifier: YOUR_PIPELINE_IDENTIFIER
  projectIdentifier: YOUR_PROJECT_IDENTIFIER
  orgIdentifier: YOUR_ORG_IDENTIFIER
  tags: {}
  stages:
    - stage:
        name: Resolve input variables
        identifier: Resolve_input_variables
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |+
                          echo "Displaying input variables"

                          # Printing the first variable defined as pipeline variable
                          echo "Environment_name = <+pipeline.variables.Environment_name>"

                          # Printing the second variable defined as Script Input Variables
                          echo "Infrastructure_name = <+execution.steps.ShellScript_1.spec.environmentVariables.Infrastructure_name>"

                          # Printing the third variable defined as Script Input Variables

                          echo "Use double quotes to safely handle the Harness placeholder and escape the backslash"

                          echo "custom_url_with_backslash = '<+execution.steps.ShellScript_1.spec.environmentVariables.custom_url_with_backslash>'"

                          # Printing the expression without quotes removes the backslash
                          echo "Removing quotes to remove the backslash"
                          echo "custom_url_with_backslash = "<+execution.steps.ShellScript_1.spec.environmentVariables.custom_url_with_backslash>

                    environmentVariables:
                      - name: Infrastructure_name
                        type: String
                        value: Kubernetes_infra
                      - name: custom_url_with_backslash
                        type: String
                        value: harness.io\
                    outputVariables: []
                    delegateSelectors:
                      - helm-delegate-2-vishal
                  timeout: 10m
        tags: {}
  variables:
    - name: Environment_name
      type: String
      description: ""
      required: true
      value: Stage_env

# --- example 4 ---
pipeline:
  projectIdentifier: myproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        identifier: testSimple
        type: Custom
        name: testSimple
        description: ""
        spec:
          execution:
            steps:
              - stepGroup:
                  identifier: stepGroup1
                  name: stepGroup1
                  steps:
                    - step:
                        identifier: ShellScript_1
                        type: ShellScript
                        name: ShellScript_1
                        spec:
                          shell: Bash
                          onDelegate: true
                          source:
                            type: Inline
                            spec:
                              script: |-
                                var1="val1"
                                var2="val2"
                          environmentVariables: []
                          outputVariables:
                            - name: var1
                              type: String
                              value: var1
                            - name: var2
                              type: String
                              value: var2
                          outputAlias:
                            key: info
                            scope: StepGroup
                        timeout: 10m
                    - step:
                        type: ShellScript
                        name: outputs
                        identifier: outputs
                        spec:
                          shell: Bash
                          onDelegate: true
                          source:
                            type: Inline
                            spec:
                              script: |-
                                echo "reference using aliases:"

                                echo "var1:" <+exportedVariables.getValue("stepGroup.info.var1")>
                                echo "var2:" <+exportedVariables.getValue("stepGroup.info.var2")>
                                echo "var map:" <+exportedVariables.getValue("stepGroup.info")>

                                echo "reference using standard output exp:"

                                echo "var1:" <+pipeline.stages.testSimple.spec.execution.steps.stepGroup1.steps.ShellScript_1.output.outputVariables.var1>
                                echo "var2:" <+pipeline.stages.testSimple.spec.execution.steps.stepGroup1.steps.ShellScript_1.output.outputVariables.var2>
                          environmentVariables: []
                          outputVariables: []
                        timeout: 10m
        tags: {}
  identifier: StepGroupExport
  name: StepGroupExport
