# source: docs/continuous-delivery/cd-onboarding/new-user/convert-jenkins-pipeline-to-harness.md  (https://developer.harness.io/docs/continuous-delivery/cd-onboarding/new-user/convert-jenkins-pipeline-to-harness)

# --- example 1 ---
pipeline:
  name: Harness CD
  identifier: Harness_CD
  projectIdentifier: default
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.Harness_Kubernetes_Cluster
              namespace: build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: "Build And Push Docker Registry "
                  identifier: Build_And_Push_Docker_Registry
                  spec:
                    connectorRef: account.harnessImage
                    repo: harness/nginx
                    tags:
                      - latest
    - stage:
        name: Deploy To Dev
        identifier: Deploy_To_Dev
        description: "Deploy NGINX Service to Dev Environment"
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginx
          environment:
            environmentRef: k8sdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev
                inputs:
                  identifier: dev
                  type: KubernetesDirect
                  spec:
                    namespace: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Deploy to QA
        identifier: Deploy_to_QA
        description: "Deploy NGINX Service to QA Environment"
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            useFromStage:
              stage: Deploy_To_Dev
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: qa
            deployToAll: false
            infrastructureDefinitions: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Deploy to Prod
        identifier: Deploy_to_Prod
        description: "Deploy NGINX Service to Prod Environment"
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            useFromStage:
              stage: Deploy_To_Dev
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: k8sprod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: prod
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: <+input>
        build: <+input>

# --- example 2 ---
service:
  name: nginx
  identifier: nginx
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: nginx
            type: K8sManifest
            spec:
              store:
                type: Harness
                spec:
                  files:
                    - /deployment.yaml
                    - /namespace.yaml
                    - /service.yaml
              valuesPaths:
                - /values_nginx_<+env.name>.yaml

              skipResourceVersioning: false
              enableDeclarativeRollback: false
  gitOpsEnabled: false
