# source: docs/platform/secrets/secrets-management/secrets-and-log-sanitization.md  (https://developer.harness.io/docs/platform/secrets/secrets-management/secrets-and-log-sanitization)

# --- example 1 ---
apiVersion: v1
kind: Secret
metadata:
    name: harness-example
stringData:
    key2: '***'
