# source: docs/platform/delegates/secure-delegates/trust-store-override-for-delegates.md  (https://developer.harness.io/docs/platform/delegates/secure-delegates/trust-store-override-for-delegates)

# --- example 1 ---
...
apiVersion: apps/v1
kind: StatefulSet
...
spec:
  ...
    spec:
      ...
        env:
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Xms64M"
...

# --- example 2 ---
      ...
        env:
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Xms64M -Djavax.net.ssl.trustStore=<path/to/trustStore.jks> -Djavax.net.ssl.trustStoreType=jks -Djavax.net.ssl.trustStorePassword=<password>"
...
